OrderManagement/OrderManagement/Controllers/CartController.cs
using BusinessLogic.Paging;
using BusinessLogic.Services;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;

namespace OrderManagement.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult LoadData(DataTableAjaxPostModel model)
        {
            if (model.search == null)
            {
                model.search = new Search { value = "" };
            }
            int totalRecords;
            int recordsFiltered;
            string currentUserId = User.Identity.GetUserId();
            var cartData = new CartService().GetPaginated(model, currentUserId, out totalRecords, out recordsFiltered);
            return Json(new
            {
                draw = model.draw,
                recordsTotal = totalRecords,
                recordsFiltered = recordsFiltered,
                data = cartData

            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCart(DataTableAjaxPostModel model)
        {
            if (model.search == null)
            {
                model.search = new Search { value = "" };
            }
            string currentUserId = User.Identity.GetUserId();
            var data = new CartService().GetProductsInCart(currentUserId);
            return Json(new
            {
                data = data

            }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult DeleteFromCart(int id)
        {
            using (var cartService = new CartService())
            {
                cartService.Delete(id);
                return RedirectToAction("Index");
            }
        }
    }
}

OrderManagement/OrderManagement/Views/Cart/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
</head>
@if (Context.User.Identity.IsAuthenticated)
{
    <body>
        <div class='page-header'>
            <div class='btn-toolbar pull-right'>
                <div class='btn-group'>
                    <input type='button' value="Make and Order" class='btn btn-primary' onclick="location.href='@Url.Action("Index", "Cart")'" />
                </div>
            </div>
            <h2>Your Cart</h2>
        </div>

        <div class="table-responsive">
            <table id="cartTable" class='table dt-responsive'>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>ProductId</th>
                        <th>Product Name</th>
                        <th>Quantity</th>
                        <th>Delete</th>
                        <th>UserId</th>
                        <th>UserName</th>
                    </tr>
                </thead>
            </table>
        </div>
    </body>
}
</html>


@* Load css *@
<link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="//cdn.datatables.net/responsive/2.2.0/css/responsive.bootstrap.min.css" rel="stylesheet" />


@* load js *@
@section Scripts{
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.0/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.0/js/responsive.bootstrap.min.js"></script>
}